nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%'] # Ou ['*'] pour tester
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: [ '*' ] # Ou l'URL de votre app React
            allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]
            max_age: 3600
